version: '3'
services:
  frontend-service:
    restart: always
    build:
      context: ./api_gateway/gateway
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/api-gateway

  nginx:
    build:
      context: ./api_gateway/nginx
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - frontend-service

  about_service:
    container_name: file-services
    build:
      context: ./file_service
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    env_file:
      - ./file_service/.env
    volumes:
      - .:/file-service
