version: '3'
services:
  frontend_service:
    container_name: frontend_service
    restart: always
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/api-gateway

  nginx_service:
    container_name: api_gateway
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:8080
