version: '3.9'

services:
  about_service:
    container_name: file-services
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    env_file:
      - .env
    volumes:
      - .:/file-service
