version: '3.9'

services:
  file_service:
    container_name: file_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    env_file:
      - .env
    volumes:
      - .:/file_service
