version: '3'
services:
  feedback_service:
    container_name: feedback_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    env_file:
      - .env
    volumes:
      - .:/feedback_service
